import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="min-h-screen w-full" style={{ backgroundColor: "#fafafa" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col max-w-5xl mx-auto justify-center items-center gap-12 py-10">
        <Image src="/logo.png" width={200} height={150} />
        <form className="w-full md:px-60 px-10">
          <label className="flex flex-col mb-4" htmlFor="question1">
            <span className="text-gray-800 mb-1">Ποιά προϊόντα επιλέξατε;</span>
            <textarea
              className="border border-gray-200 shadow-sm"
              name=""
              id=""
              cols="20"
              rows="2"
            ></textarea>
          </label>
          <label className="flex flex-col mb-6" htmlFor="question1">
            <span className="text-gray-800 mb-1">
              Μιλήστε μας για την εμπειρία σας:
            </span>
            <textarea
              className="border border-gray-200 shadow-sm"
              name=""
              id=""
              cols="20"
              rows="5"
            ></textarea>
          </label>
          <button
            type="submit"
            className="w-full py-4 bg-purple-btn hover:bg-purple-btnH transition duration-200 rounded-sm shadow-sm"
          >
            Αποστολή
          </button>
        </form>
      </main>
    </div>
  );
}
