import Head from "next/head";
import { useRef, useState, useEffect } from "react";
import Image from "next/image";
import Spinner from "../components/Spinner";

export default function Home() {
  const q1Ref = useRef();
  const q2Ref = useRef();
  const [loading, setLoading] = useState(false);
  const [mailSent, setMailSent] = useState(false);
  const handleSubmit = (e) => {
    e.preventDefault();
    setLoading(true);
    const q1 = q1Ref.current.value;
    const q2 = q2Ref.current.value;
    const data = {
      q1,
      q2,
    };
    fetch("/api/mail", {
      method: "POST",
      headers: {
        Accept: "application/json, text/plain, */*",
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    }).then((res) => {
      if (res.status === 200) {
        localStorage.setItem("isSent", true);
        setLoading(false);
      } else {
        setLoading(false);
        console.log(res);
        alert("Κάτι πήγε λάθος με την αποστολή της φόρμας.");
      }
    });
  };

  useEffect(() => {
    if (typeof window !== "undefined") {
      setMailSent(localStorage.getItem("isSent"));
    }
  });

  return (
    <div
      className="min-h-screen w-full font-Jura"
      style={{ backgroundColor: "#fafafa" }}
    >
      <Head>
        <title>Duos Dei - Ερωτηματολόγιο</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <main className="flex flex-col max-w-5xl mx-auto justify-center items-center gap-12 py-10">
        <Image src="/logo.png" width={200} height={150} priority />
        <form onSubmit={handleSubmit} className="w-full md:px-60 px-10">
          <label className="flex flex-col mb-4" htmlFor="question1">
            <span className="text-gray-700 mb-1">Ποιά προϊόντα επιλέξατε;</span>
            <textarea
              ref={q1Ref}
              className="border border-slate-200 shadow-sm focus:border-slate-400 p-1  focus:outline-none"
              name=""
              id=""
              cols="20"
              maxLength={100}
              rows="2"
            ></textarea>
          </label>
          <label className="flex flex-col mb-6" htmlFor="question1">
            <span className="text-gray-700 mb-1">
              Μιλήστε μας για την εμπειρία σας:
            </span>
            <textarea
              ref={q2Ref}
              className="border border-slate-200 shadow-sm focus:border-slate-400 p-1 focus:outline-none"
              name=""
              maxLength={400}
              id=""
              cols="20"
              rows="5"
            ></textarea>
          </label>
          {mailSent ? (
            <button
              disabled={true}
              className="w-full text-center py-4 text-slate-100 bg-slate-700"
            >
              Ευχαριστούμε για τον χρόνο σας!
            </button>
          ) : (
            <button
              disabled={loading}
              type="submit"
              className={
                loading
                  ? "w-full text-center py-4 text-gray-700 bg-purple-btn transition-all duration-200"
                  : " w-full text-center py-4 text-gray-700 bg-purple-btn hover:bg-purple-btnH transition duration-200 rounded-sm shadow-sm"
              }
            >
              {loading ? <Spinner /> : "Αποστολή"}
            </button>
          )}
        </form>
      </main>
    </div>
  );
}
