import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div
      className="min-h-screen w-full font-Jura"
      style={{ backgroundColor: "#fafafa" }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <main className="flex flex-col max-w-5xl mx-auto justify-center items-center gap-12 py-10">
        <Image src="/logo.png" width={200} height={150} priority />
        <form className="w-full md:px-60 px-10">
          <label className="flex flex-col mb-4" htmlFor="question1">
            <span className="text-gray-700 mb-1">Ποιά προϊόντα επιλέξατε;</span>
            <textarea
              className="border border-gray-200 shadow-sm focus:border-gray-400  focus:outline-none"
              name=""
              id=""
              cols="20"
              rows="2"
            ></textarea>
          </label>
          <label className="flex flex-col mb-6" htmlFor="question1">
            <span className="text-gray-700 mb-1">
              Μιλήστε μας για την εμπειρία σας:
            </span>
            <textarea
              className="border border-gray-200 shadow-sm focus:border-gray-400 focus:outline-none"
              name=""
              id=""
              cols="20"
              rows="5"
            ></textarea>
          </label>
          <button
            type="submit"
            className="w-full py-4 text-gray-700 bg-purple-btn hover:bg-purple-btnH transition duration-200 rounded-sm shadow-sm"
          >
            Αποστολή
          </button>
        </form>
      </main>
    </div>
  );
}
